# Generated by Django 5.2 on 2025-05-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frottis',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
