# Generated by Django 5.2 on 2025-05-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frottis',
            name='status',
            field=models.CharField(max_length=255),
        ),
    ]
