# Generated by Django 5.2 on 2025-05-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malaria', '0002_frottis_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frottis',
            name='status',
            field=models.CharField(max_length=255),
        ),
    ]
